[program:volo_pi05]
environment=PROC_NAME="%(program_name)s"
command=/workspace/volo_repro/scripts/serve_pi05.sh
autostart=false
autorestart=unexpected
startsecs=10
startretries=1
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0

[program:volo_orch]
environment=PROC_NAME="%(program_name)s"
command=/workspace/volo_repro/scripts/serve_orch.sh
autostart=false
autorestart=unexpected
startsecs=3
startretries=1
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
