#!/bin/bash
unset VOLO_VULKAN_COMPAT VK_ADD_IMPLICIT_LAYER_PATH VK_KHRONOS_PROFILES_PROFILE_DIRS VK_KHRONOS_PROFILES_PROFILE_NAME VK_KHRONOS_PROFILES_SIMULATE_CAPABILITIES
export VOLO_ALLOCATION_COMPAT=1
export XDG_DATA_DIRS=/root/volo-repro/compat/narrow/share:/usr/local/share:/usr/share
